#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later OR Apache-2.0 OR MIT
# SPDX-FileCopyrightText: 2024 Charles Wong <charlie-wong@outlook.com>
# Repository: https://github.com/charlie-wong/zeta
#
# Copy to /etc/grub.d/11-prober-macos
